spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username : sa
    password :
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:\\temp\\spring_upload_files

server:
  port: 8080

mybatis:
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
  mapper-locations:
    classpath*:mappers/**/*Dao.xml
  type-aliases-package:
    com.system.testProject.demo

file:
  path: C:/Temp/upload/